### ISSUE TITLE
Mute icon in voice channels doesn't show up.

### ISSUE THREAD

**Issue by Dimostheenis** [revoltchat/desktop#12] opened 2021-08-17 18:10 UTC
If you're in a server's voice channel and you after you unmute you try to re-mute, the icon doesn't show up, or you don't even mute. I'm talking about the mute icon at the bottom right corner of your profile picture inside the voice channel.

**Comment by ryanalexander** [comment] 2021-08-20 02:29
Duplicate of issue 
https://github.com/revoltchat/revite/issues/89

**Closed** 2021-08-20 02:32 UTC
