### ISSUE TITLE
Strange glitch on startup

### ISSUE THREAD

**Issue by 10allday** [revoltchat/desktop#22] opened 2021-09-12 12:14 UTC
The one with white and black happens on startup of the desktop app.
https://autumn.revolt.chat/attachments/Ivdg-EI2Fpe1hAwRLEcl7_B_tK5t0NsPn7Hy-gDleM/bruh.PNG.jpg

It goes white when it's minimized, and you reopen the program. (After few secs shows the loading dots.)
https://autumn.revolt.chat/attachments/7keq3qnlDfKw22lW5m5cunAOf9AMrRIM-tg_DO2Krd/bruh.jpg

**Comment by insertish** [comment] 2021-10-09 22:33
Duplicate of #14

**Closed by insertish** 2021-10-09 22:33 UTC
Labels: duplicate
