### ISSUE TITLE
bug: The desktop app will not close (MAC)

### ISSUE THREAD

**Issue by e7a-0-e7a** [revoltchat/desktop#127] opened 2023-01-17 07:13 UTC
### What happened?

Hello,

I have the Revoltchat desktop app for Mac. However, the app does not close properly. As a result, I can no longer shut down my MAC properly.

**Comment by Rexogamer** [comment] 2023-01-17 11:05
Duplicate of #116.

**Closed by Rexogamer** 2023-01-17 11:05 UTC
Labels: bug
