### ISSUE TITLE
feature request: Add url switch box for self hosted instance

### ISSUE THREAD

**Issue by Anthanaab** [revoltchat/desktop#150] opened 2023-05-21 22:04 UTC
### What do you want to see?

Hello,

Possibility to add an option to enter a custom url for self hosted instance ? because build the client is not "easy to use"

Thanks you.

Regards,

Antha

**Comment by GanimanSwift** [comment] 2023-07-07 16:39
Please consider adding this feature. Without this, the clients will potentially become fragmented as more and more self hosted instances are set up and are required to fork the clients to change a few lines of code. Without this kind of feature the potential of Revolt is limited.

**Comment by Rexogamer** [comment] 2023-07-07 20:51
Duplicate of #53.

**Closed by Rexogamer** 2023-07-07 20:51 UTC
Labels: enhancement
