### ISSUE TITLE
bug: Mic and speaker permission error

### ISSUE THREAD

**Issue by vimalraj27** [revoltchat/desktop#132] opened 2023-03-14 18:30 UTC
### What happened?

The "You need to grant permission to access audio settings" pop up keeps reappearing even after selecting the mic and speaker. This happens once I select the respective devices and leave that particular page / menu.

Screenshot:
![image](https://user-images.githubusercontent.com/95607390/225103268-7c8a3aa6-4058-40f3-a652-4fdc25ffc0e8.png)

**Comment by stationaryStation** [comment] 2023-03-14 19:53
Duplicate of revoltchat/revite [#459](https://github.com/revoltchat/revite/issues/459)

The issue will most definitely fixed in the new Client/Voice Server rewrite.

**Comment by stationaryStation** [comment] 2023-03-14 19:56
Also, this is not an issue that is part of the desktop client as it happens on browsers, mobile and desktop.

**Closed** 2023-03-14 20:10 UTC
Labels: bug

**Comment by MimikFc7** [comment] 2024-10-11 07:52
Hello, same trouble. Linux, Fedora 39 core 6.10.12-100.fc39.x86_64, Xfce desktop, 
Nightly 1.0.1
Native: 1.0.6
API: 0.7.14
revolt.js: 6.0.17
