### ISSUE TITLE
bug: text/voice channel and role is duplicated when making one

### ISSUE THREAD

**Issue by kyronsaif** [revoltchat/desktop#107] opened 2022-08-29 07:37 UTC
### What happened?

When I go to create a Text/Voice Channel, a duplicate is made and put into the Uncategorized section. Then if I create a Role, it creates a duplicate of the one I just made.
![Dupe Chat 1](https://user-images.githubusercontent.com/75399247/187148711-1f981745-5522-453a-b87d-71f4e02625e4.PNG)
![Dupe Chat 2](https://user-images.githubusercontent.com/75399247/187148745-214d2f96-7552-4e8c-9a9b-635e74f02ca5.PNG)
![Dupe Role](https://user-images.githubusercontent.com/75399247/187148763-82006eb1-9876-4f28-9d3b-76d1c4f1e960.PNG)

**Comment by Rexogamer** [comment] 2022-08-29 10:37
Duplicate of revoltchat/revite#748.

**Closed by Rexogamer** 2022-08-29 10:37 UTC
Labels: bug
