### ISSUE TITLE
feature request: Native app

### ISSUE THREAD

**Issue by ALipAkrohk** [revoltchat/desktop#105] opened 2022-08-17 14:12 UTC
### What do you want to see?

Please leave electron and use GTK or Flutter.
The biggest problem of Discord is the existence of Electron, you will definitely be its biggest competitor in the future, but you carry that problem with you.
While node.js has the ability to use the GTK library, why do you still make software using electron?
---------------------------------------------------
### node.JS/TS
https://www.npmjs.com/package/node-gtk

### Python
https://pygobject.readthedocs.io/en/latest/
https://flet.dev/
https://www.riverbankcomputing.com/software/pyqt/

### Rust
https://gtk-rs.org/
https://www.rustwithflutter.com/

### Dart
https://flutter.dev/
https://pub.dev/documentation/gtk/latest/

**Comment by ggtylerr** [comment] 2022-08-17 14:15
Duplicate of #4

**Comment by ALipAkrohk** [comment] 2022-08-17 14:37
These two issues are really different, the request to move to a native framework versus the request to replace Electron with other runtime instances.
The question that comes to me is that when flutter gives you the ability to build native software so easily, why do you still use electron and similar examples (the same for GTK)?

**Comment by ggtylerr** [comment] 2022-08-17 15:02
I feel like the two are similar enough to be merged. Both are regarding alternatives to the current framework.

Moving to a different web-based framework is a million times simpler than (usually) moving to a new language and framework. The simplest one you listed (node-gtk) is still in an early state, everything else will require a new language, even Dart requires a new library (the current one does not support normal logins)

Also, hCaptcha. I'm not sure if you can implement it in GTK / Flutter but I'm not 100% on that.

**Comment by ALipAkrohk** [comment] 2022-08-17 15:42
> Also, hCaptcha. I'm not sure if you can implement it in GTK / Flutter but I'm not 100% on that.
It is possible to use hCaptcha in node-gtk by calling its [library](https://github.com/vastus/node-hcaptcha), but in flutter with python or dart or rust

https://pub.dev/packages/hcaptcha/
https://pypi.org/project/librecaptcha/
https://docs.rs/hcaptcha/latest/hcaptcha/

**Comment by Rexogamer** [comment] 2022-08-17 16:09
I'm going to close this out as a duplicate of #4 - feel free to cross-post your suggestions ^^

**Closed by Rexogamer** 2022-08-17 16:09 UTC
Labels: enhancement
