### ISSUE TITLE
feature request: Connecting stuff to profile

### ISSUE THREAD

**Issue by oliviathevampire** [revoltchat/desktop#156] opened 2023-06-12 08:43 UTC
### What do you want to see?

I would love a way for us to be able to connect stuff like GitHub, Reddit, Twitter, etc and being able to show them on our profile, maybe even for roles being able to use those connections for different requirements, like let's say we have a channel for people with a lot of reddit karma, you would be able to for example say, this channel is only for people with over 10.000 reddit karma.

**Comment by Rexogamer** [comment] 2023-07-07 20:47
Duplicate of [revoltchat/discussions#272](https://github.com/orgs/revoltchat/discussions/272).

**Closed by Rexogamer** 2023-07-07 20:47 UTC
Labels: enhancement
